import { MdEventAvailable } from 'react-icons/md'

const momenceUrl = Rule =>
  Rule.uri({
    scheme: ['https'],
    allowRelative: false
  }).custom(value => {
    if (!value) return true

    try {
      const host = new URL(value).hostname
      return host === 'momence.com' || host.endsWith('.momence.com')
        ? true
        : 'Use an HTTPS Momence URL.'
    } catch (error) {
      return 'Use a valid HTTPS Momence URL.'
    }
  })

const idArray = (name, title) => ({
  name,
  title,
  type: 'array',
  of: [
    {
      type: 'string',
      validation: Rule => Rule.regex(/^\d+$/, { name: 'numeric ID' })
    }
  ],
  validation: Rule => Rule.unique()
})

export default {
  name: 'settingsMomence',
  title: 'Momence',
  type: 'document',
  icon: MdEventAvailable,
  fields: [
    {
      name: 'accountUrl',
      title: 'Account sign-in URL',
      type: 'url',
      initialValue: 'https://momence.com/sign-in',
      validation: momenceUrl
    },
    {
      name: 'videoLibraryUrl',
      title: 'Video Library URL',
      description: 'Paste the public Video Library URL generated by Momence.',
      type: 'url',
      validation: momenceUrl
    },
    {
      name: 'giftCardUrl',
      title: 'Gift Card URL',
      type: 'url',
      validation: momenceUrl
    },
    {
      name: 'scheduleUrl',
      title: 'Public schedule fallback URL',
      description: 'The public Hipline schedule page copied from Momence.',
      type: 'url',
      initialValue: 'https://momence.com/u/hipline-zNlk68',
      validation: momenceUrl
    },
    {
      name: 'allowedEmbedHosts',
      title: 'Approved iframe hostnames',
      description: 'Hostnames only, without https:// or a path. Momence is always approved.',
      type: 'array',
      of: [
        {
          type: 'string',
          validation: Rule => Rule.regex(/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i)
        }
      ],
      validation: Rule => Rule.unique()
    },
    {
      name: 'schedule',
      title: 'Schedule plugin defaults',
      type: 'object',
      options: { collapsible: true, collapsed: false },
      fields: [
        {
          name: 'hostId',
          title: 'Host ID',
          type: 'string',
          validation: Rule => Rule.required().regex(/^\d+$/, { name: 'numeric host ID' })
        },
        idArray('teacherIds', 'Teacher IDs'),
        idArray('locationIds', 'Location IDs'),
        idArray('tagIds', 'Tag IDs'),
        {
          name: 'defaultFilter',
          title: 'Default filter',
          type: 'string',
          initialValue: 'show-all',
          validation: Rule => Rule.regex(/^[a-z0-9-]+$/i)
        },
        {
          name: 'locale',
          title: 'Locale',
          type: 'string',
          initialValue: 'en',
          validation: Rule => Rule.regex(/^[a-z]{2}(-[A-Z]{2})?$/)
        }
      ]
    }
  ]
}
